// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1fEORIAxMNxYRKSgiWpyCRt_7EUv2FBM',
    appId: '1:731033508145:web:ca04017599fe4a5bfaf810',
    messagingSenderId: '731033508145',
    projectId: 'methompson-site',
    authDomain: 'methompson-site.firebaseapp.com',
    storageBucket: 'methompson-site.appspot.com',
    measurementId: 'G-WQHY4DX8HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeGKhI-pl-OET1XdUX2L4pLH4z60eGSc',
    appId: '1:731033508145:android:a14a7b43c35b4535faf810',
    messagingSenderId: '731033508145',
    projectId: 'methompson-site',
    storageBucket: 'methompson-site.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SyTpu9MiOcCjwUqrjMrJ6-XCQzn1n_k',
    appId: '1:731033508145:ios:e82f9fe13314a192faf810',
    messagingSenderId: '731033508145',
    projectId: 'methompson-site',
    storageBucket: 'methompson-site.appspot.com',
    iosBundleId: 'com.example.flutterBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1SyTpu9MiOcCjwUqrjMrJ6-XCQzn1n_k',
    appId: '1:731033508145:ios:e82f9fe13314a192faf810',
    messagingSenderId: '731033508145',
    projectId: 'methompson-site',
    storageBucket: 'methompson-site.appspot.com',
    iosBundleId: 'com.example.flutterBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1fEORIAxMNxYRKSgiWpyCRt_7EUv2FBM',
    appId: '1:731033508145:web:5b4bed4ee32a1b8dfaf810',
    messagingSenderId: '731033508145',
    projectId: 'methompson-site',
    authDomain: 'methompson-site.firebaseapp.com',
    storageBucket: 'methompson-site.appspot.com',
    measurementId: 'G-CHC3JNRS3T',
  );

}